### ISSUE TITLE
duplicate messages

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dash-ui-sequence-viewer#1]
Here's a set of data that's causing duplicate messages.

https://gist.github.com/jedgalbraith/6e18804b5b6a0a5f78a3de749e5183b3

And here's a screenshot of what it looks like.

![screen shot 2016-10-18 at 2 27 40 pm](https://cloud.githubusercontent.com/assets/313947/19495735/e1450a56-9541-11e6-814b-e4a72654cff4.png)

**Comment by Tolmark12** [comment]
When I look at the json, I see two sequences being passed, which would result in two sequences visually:

```
# data.db : 
test-comp-users/data.db

# data.db.1 :
test-comp-users/data.db/1/1-update
```

Does that sound right?

**Comment by Tolmark12** [comment]
found in : [258.json](https://gist.github.com/jedgalbraith/6e18804b5b6a0a5f78a3de749e5183b3#file-258-json)

**Comment by jedgalbraith** [comment]
Yes, there should be two sequences visually. The problem is that both sequences have the same message(updating component) when they should be different. So it's like the message from one is being used for the other. The message for data.db.1 should be "ensuring instance has latest binaries".

**Comment by Tolmark12** [comment]
When I test locally, I'm unable to replicate it so they have the same message, I see : 
![screenshot](http://image.prntscr.com/image/cd7541bd6c8b403094955260e09a0358.png)

**Comment by jedgalbraith** [comment]
I can't replicate this any more either. It must have been a fluke or something has changed since. I'll created another issue if it happens again.
