### ISSUE TITLE
update move data component options

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dash-ui-sequence-viewer#4]
Now that moving a component to a new single component cluster is an option, the logic for displaying which options are available needs to be updated. Currently, they're only displayed if there are multiple bunkhouses. A "New Single-component Host" should be an option when there's a single bunkhouse.

Single Bunkhouse
![screen shot 2016-11-09 at 11 34 34 am](https://cloud.githubusercontent.com/assets/313947/20151189/7861603e-a676-11e6-8eed-febcc85e00f0.png)

Multiple Bunkhouses
![screen shot 2016-11-08 at 3 59 03 pm](https://cloud.githubusercontent.com/assets/313947/20151227/951ef36c-a676-11e6-9533-1f73c621db3f.png)

**Comment by Tolmark12** [comment]
Fixed / built, waiting for deploy
