### ISSUE TITLE
cancel button lifecycle

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dash-ui-sequence-viewer#7]
Sometimes it takes a while for the state of the sequence viewer to update after hitting "Cancel !", so it would help if there was some kind of lifecycle or feedback when you clicked it. Otherwise it can seem like it isn't doing anything or that you need to hit it again.

![](http://g.recordit.co/0l4tGfugfb.gif)

**Comment by Tolmark12** [comment]
Pushed a fix, ready for deploy

**Comment by jedgalbraith** [comment]
Cool. Thanks. That looks great on my local. I'll get it pushed up.
