### ISSUE TITLE
remove translation of status

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dash-ui-sequence-viewer#8]
@Tolmark12 Could you remove any translations of the sequence status? I think at one time I asked you to translate `waiting` to `running`. I'm refactoring the status and I'll just handle any translations on my side.

**Comment by Tolmark12** [comment]
I see this piece of code:
```coffeescript
  formatStatus : (status)->
    switch status
      when 'queued', 'errored'
        return status
      else
        return 'Running'
```
To be clear, I always just show the status that is passed in?

**Comment by Tolmark12** [comment]
(Assuming the above is correct, pushed ready for deploy)

**Comment by jedgalbraith** [comment]
Yes, that is correct. Thanks.
